spring:
  application:
    name: CampusPulseAi

  datasource:
    url: jdbc:postgresql://localhost:5432/campuspulseai   #jdbc:postgresql://localhost:3307/campus_pulse
    username: postgres
    password: qeema**123 #postgres
    driver-class-name: org.postgresql.Driver


