spring:
  application:
    name: CampusPulseAi

  jwt:
    secret: your_base64_encoded_secret_key
    expiration: 86400000 # 1 day in ms

  datasource:
    url: jdbc:postgresql://localhost:3307/campus_pulse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui:
    path: /docs


